default: &default
  encoding: utf8
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: open_api_development

test:
  <<: *default
  database: open_api_test
